filter:
    excluded_paths:
        - 'vendor/*'
tools:
    php_mess_detector: true
    php_cs_fixer: true
    php_analyzer: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_cpd: true
    php_loc: true
    php_pdepend: true
    external_code_coverage: true
